require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config.ru"
    - "config/**/*"
    - "Rakefile"
    - "vendor/**/*"
  NewCops: enable

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false
